# 为了往官方的镜像里添加一些依赖包,而写的Dockfile

FROM rasa/rasa-sdk:2.8.2  
# 官方提供的sdk镜像
USER root
# 切换到root用户,不然pip会报错
COPY requirements.txt /home
# 把requirements.txt复制进来
# RUN apt-get update \
#     && apt-get install sudo \
#     && sh -c '/bin/echo -e "\nY" | sudo apt install build-essential' \
#     && sudo apt-get install python3-dev \
#     && sudo -H pip install --no-cache-dir -r /home/requirements.txt   

RUN apt-get update -qq && \
    apt-get install sudo && \
    sh -c '/bin/echo -e "\nY" | sudo apt install -y build-essential' && \
    sudo apt-get install -y python3-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
# 这里坑也不少,虽然是按照官方文档写的,但是不加sudo的话,会报各种错,即便是root用户也不行

RUN pip install --no-cache-dir -r /home/requirements.txt

USER 1001 